### ISSUE TITLE
请问词嵌入的时候是对pdg还是对切片后的pdg子图做嵌入

### ISSUE THREAD

**Issue by 664730** [Stwsyburg/Vuldetexp#10]
pdg子图的话我试了没有输出json图，希望作者能解惑，感谢！

**Comment by suywang** [comment]
对pdg嵌入就是函数级，对子图嵌入就是切片级，你自己调试一下把看看为什么没有输出

**Comment by 664730** [comment]
> 对pdg嵌入就是函数级，对子图嵌入就是切片级，你自己调试一下把看看为什么没有输出

感谢作者的回复，已经输出了，谢谢!
