### ISSUE TITLE
train_w2v.py

### ISSUE THREAD

**Issue by funssie** [Stwsyburg/Vuldetexp#6]
FileNotFoundError: [Errno 2] No such file or directory config.yaml
Could you provide config.yaml?

**Comment by 664730** [comment]
> FileNotFoundError: [Errno 2] No such file or directory config.yaml Could you provide config.yaml?

May I ask if you have received config.yaml? Thank you

**Comment by suywang** [comment]
I have uploaded config.yaml, sorry

**Comment by 664730** [comment]
I see it, thank you very much


charming
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Stwsyburg/Vuldetexp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Stwsyburg/Vuldetexp] train_w2v.py (Issue #6)





 
I have uploaded config.yaml, sorry

**Comment by 664730** [comment]
May I ask if you could send me the trained word2vec model? It always crashes after six hours of training. Thank you very much




charming
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Stwsyburg/Vuldetexp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Stwsyburg/Vuldetexp] train_w2v.py (Issue #6)





 
I have uploaded config.yaml, sorry
