### ISSUE TITLE
请问一下生成w2v.wv的过程中出现这个问题正常吗？

### ISSUE THREAD

**Issue by 664730** [Stwsyburg/Vuldetexp#9]
pdg paths: 22%|█████████████████▉ | 23744/106183 [29:37<1:03:21, 21.68it/s]"1000181" -> "1000180" [label="DDG: \".xn--\""];
^
Expected graph_stmt, found '[' (at char 1473), (line:25, col:25)
还有我最后得到了两个文件w2v.wv.vectors.npy和w2v.wv这个正常吗？希望有人能回复，谢谢！

**Comment by 664730** [comment]
我用这两个文件生成词嵌入的json图都有问题，node_features为空

**Comment by lingxi66** [comment]
你好我想问问你使用的joern的版本是多少，作者给的joern-cli_v1.1.172，不清楚具体是多少，然后我现在和那个作者给的graph-for-funcs.sc对应不上，后续切片处理就一直有问题，期待你的回复谢谢！

**Comment by 664730** [comment]
> 你好我想问问你使用的joern的版本是多少，作者给的joern-cli_v1.1.172，不清楚具体是多少，然后我现在和那个作者给的graph-for-funcs.sc对应不上，后续切片处理就一直有问题，期待你的回复谢谢！

你加我vx吧charmingyyg

**Comment by 664730** [comment]
> pdg paths: 22%|█████████████████▉ | 23744/106183 [29:37<1:03:21, 21.68it/s]"1000181" -> "1000180" [label="DDG: ".xn--""]; ^ Expected graph_stmt, found '[' (at char 1473), (line:25, col:25) 还有我最后得到了两个文件w2v.wv.vectors.npy和w2v.wv这个正常吗？希望有人能回复，谢谢！
